builds:
  - id: nurse
    binary: nurse
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

force_token: gitea
release:
  gitea:
    owner: prskr
    name: nurse
  ids:
    - nurse
  mode: replace
  extra_files:
    - glob: ./nurse.yaml

dockers:
  - ids:
      - nurse
    image_templates:
      - code.icb4dc0.de/prskr/nurse:latest
      - code.icb4dc0.de/prskr/nurse:{{ .Tag }}
      - code.icb4dc0.de/prskr/nurse:{{ .Major }}
      - code.icb4dc0.de/prskr/nurse:{{ .ShortCommit}}
    dockerfile: deployments/Dockerfile

gitea_urls:
  api: https://code.icb4dc0.de/api/v1
  download: https://code.icb4dc0.de
