builds:
  - id: nurse
    binary: nurse
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

force_token: gitea
release:
  gitea:
    owner: prskr
    name: nurse
  ids:
    - nurse
  mode: replace
  extra_files:
    - glob: ./nurse.yaml

archives:
  - id: nurse
    builds:
      - nurse
    format: tar.gz

kos:
  - id: nurse
    build: nurse
    repository: code.icb4dc0.de/prskr
    platforms:
      - linux/amd64
      - linux/arm64
    tags:
      - "latest"
      - "{{ .Tag }}"
      - "{{ .Major }}"
      - "{{ .ShortCommit}}"
    bare: true
    preserve_import_paths: false
    base_import_paths: true

gitea_urls:
  api: https://code.icb4dc0.de/api/v1
  download: https://code.icb4dc0.de
