---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: docker.io/golangci/golangci-lint
    tag: latest

inputs:
  - name: repo
    path: .

params:
  GO111MODULE: "on"
  CGO_ENABLED: "0"
  GITEA_TOKEN: ((gitea-credentials.token))

run:
  path: bash
  args:
    - -ce
    - |
      golangci-lint run -v
