version: v0
runs:
  - name: Renovate deps
    when:
      branch: main
    tasks:
      - name: Run renovate
        runtime:
          containers:
            - image: docker.io/renovate/renovate
        environment:
          RENOVATE_PLATFORM: gitea
          RENOVATE_AUTODISCOVER: 'false'
          RENOVATE_ENDPOINT: https://code.icb4dc0.de/api/v1
          LOG_LEVEL: info
          RENOVATE_TOKEN:
            from_variable: gitea-token
          GITHUB_COM_TOKEN:
            from_variable: github-token
        steps:
          - run:
              name: Run bot
              command: renovate prskr/nurse
  - name: Test and lint
    tasks:
      - name: Checkout code
        runtime:
          type: pod
          containers:
            - image: docker.io/alpine/git
        steps:
          - clone:
          - save_to_workspace:
              contents:
                - source_dir: .
                  dest_dir: .
                  paths:
                    - '**'
      - name: Test
        runtime:
          type: pod
          containers:
            - image: docker.io/golang:1.19-bullseye
              environment:
                DOCKER_HOST: tcp://127.0.0.1:2375
            - image: code.icb4dc0.de/prskr/ci-images/dind:latest
              privileged: true
        steps:
          - restore_workspace:
              dest_dir: .
          - run:
              name: Install Go tools
              command: go install gotest.tools/gotestsum@latest
          - run:
              name: run all tests
              command: gotestsum -f pkgname-and-test-fails -- -race -shuffle=on ./...
        depends:
          - Checkout code

      - name: Lint code
        runtime:
          type: pod
          arch: amd64
          containers:
            - image: docker.io/golangci/golangci-lint
        environment:
          GO111MODULE: "on"
          CGO_ENABLED: "0"
        steps:
          - restore_workspace:
              dest_dir: .
          - run:
              name: Run golangci-lint
              command: golangci-lint run -v
        depends:
          - Checkout code
