version: v0
runs:
  - name: Build
    tasks:
      - name: Test
        runtime:
          type: pod
          containers:
            - image: docker.io/golang:1.19-bullseye
              environment:
                DOCKER_HOST: tcp://127.0.0.1:2375
            - image: europe-north1-docker.pkg.dev/b4dc0-355617/ci-images/dind:20.10
              privileged: true
        steps:
          - clone:
          - run:
              name: run all tests
              command: go test ./...
