version: v0
runs:
  - name: Build
    tasks:
      - name: Test
        runtime:
          type: pod
          containers:
            - image: docker.io/golang:1.19-bullseye
              environment:
                DOCKER_HOST: tcp://127.0.0.1:2375
            - image: code.icb4dc0.de/prskr/ci-images/dind:latest
              privileged: true
        steps:
          - clone:
          - run:
              name: Install Go tools
              command: go install gotest.tools/gotestsum@latest
          - run:
              name: run all tests
              command: gotestsum -f pkgname-and-test-fails -- -race -shuffle=on ./...
